[workspace]
members = ["gds", "reality"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Pat <pat@example.com>"]
license = "GPL-3.0-only"
repository = "https://github.com/pat/organon"
